[2025-08-18T23:57:27.255+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T23:57:27.284+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: crypto_collector_dag.run_crypto_collector scheduled__2025-08-18T23:56:00+00:00 [queued]>
[2025-08-18T23:57:27.294+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: crypto_collector_dag.run_crypto_collector scheduled__2025-08-18T23:56:00+00:00 [queued]>
[2025-08-18T23:57:27.294+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T23:57:27.308+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_crypto_collector> on 2025-08-18 23:56:00+00:00
[2025-08-18T23:57:27.317+0000] {standard_task_runner.py:63} INFO - Started process 219263 to run task
[2025-08-18T23:57:27.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'crypto_collector_dag', 'run_crypto_collector', 'scheduled__2025-08-18T23:56:00+00:00', '--job-id', '10000', '--raw', '--subdir', 'DAGS_FOLDER/crawl_crypto/dags_crypto.py', '--cfg-path', '/tmp/tmp36xjdif7']
[2025-08-18T23:57:27.324+0000] {standard_task_runner.py:91} INFO - Job 10000: Subtask run_crypto_collector
[2025-08-18T23:57:27.380+0000] {task_command.py:426} INFO - Running <TaskInstance: crypto_collector_dag.run_crypto_collector scheduled__2025-08-18T23:56:00+00:00 [running]> on host 1877907bc043
[2025-08-18T23:57:27.482+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='crypto_collector_dag' AIRFLOW_CTX_TASK_ID='run_crypto_collector' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T23:56:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-18T23:56:00+00:00'
[2025-08-18T23:57:27.483+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T23:57:27.498+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T23:57:27.499+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/dags/crawl_crypto/crawl_data_crypto.py']
[2025-08-18T23:57:27.512+0000] {subprocess.py:86} INFO - Output:
[2025-08-19T00:01:02.127+0000] {subprocess.py:93} INFO - 🔹 Kết nối DB...
[2025-08-19T00:01:02.128+0000] {subprocess.py:93} INFO - 🔹 Lấy top 100 crypto...
[2025-08-19T00:01:02.128+0000] {subprocess.py:93} INFO - Top 100: ['ETHUSDT', 'USDCUSDT', 'BTCUSDT', 'SOLUSDT', 'FDUSDUSDT', 'XRPUSDT', 'DOGEUSDT', 'LINKUSDT', 'ADAUSDT', 'SUIUSDT', 'BNBUSDT', 'PROVEUSDT', 'TRXUSDT', 'ENAUSDT', 'TOWNSUSDT', 'ARBUSDT', 'PEPEUSDT', 'UNIUSDT', 'AVAXUSDT', 'BIOUSDT', 'AEURUSDT', 'PENGUUSDT', 'SEIUSDT', 'LTCUSDT', 'HBARUSDT', 'POLUSDT', 'PLUMEUSDT', 'CRVUSDT', 'AAVEUSDT', 'TRUMPUSDT', 'BFUSDUSDT', 'WLDUSDT', 'DOTUSDT', 'NEARUSDT', 'BONKUSDT', 'INJUSDT', 'WIFUSDT', 'XLMUSDT', 'SUSDT', 'API3USDT', 'VIRTUALUSDT', 'LDOUSDT', 'TAOUSDT', 'MEMEUSDT', 'APTUSDT', 'SKLUSDT', 'TONUSDT', 'OPUSDT', 'FLOKIUSDT', 'ONDOUSDT', 'PENDLEUSDT', 'ETHFIUSDT', 'FETUSDT', 'EURUSDT', 'PONDUSDT', 'BCHUSDT', 'TIAUSDT', 'RAYUSDT', 'EPICUSDT', 'SHIBUSDT', 'NEIROUSDT', 'PNUTUSDT', 'ETCUSDT', 'ALGOUSDT', 'MAGICUSDT', 'ALPINEUSDT', 'EIGENUSDT', 'FILUSDT', 'XUSDUSDT', 'GALAUSDT', 'RENDERUSDT', 'JUVUSDT', 'CYBERUSDT', 'CTSIUSDT', 'CAKEUSDT', 'ASRUSDT', 'SPKUSDT', 'OGUSDT', 'TSTUSDT', 'VETUSDT', 'RUNEUSDT', 'ICPUSDT', 'MDTUSDT', 'PAXGUSDT', 'CFXUSDT', 'BERAUSDT', 'WBTCUSDT', 'MKRUSDT', 'ORDIUSDT', 'MAVUSDT', 'ATOMUSDT', 'SYRUPUSDT', 'ENSUSDT', 'AIXBTUSDT', 'RESOLVUSDT', 'ARKMUSDT', 'LAYERUSDT', 'OMUSDT', 'WCTUSDT', 'PORTOUSDT']
[2025-08-19T00:01:02.128+0000] {subprocess.py:93} INFO - 🔹 Lưu lịch sử giá vào DB bằng threading...
[2025-08-19T00:01:02.129+0000] {subprocess.py:93} INFO - ✅ SOLUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.129+0000] {subprocess.py:93} INFO - 1/100 SOLUSDT lưu OK
[2025-08-19T00:01:02.129+0000] {subprocess.py:93} INFO - ✅ DOGEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.129+0000] {subprocess.py:93} INFO - 2/100 DOGEUSDT lưu OK
[2025-08-19T00:01:02.130+0000] {subprocess.py:93} INFO - ✅ ETHUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.130+0000] {subprocess.py:93} INFO - ✅ ADAUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.130+0000] {subprocess.py:93} INFO - 3/100 ETHUSDT lưu OK
[2025-08-19T00:01:02.131+0000] {subprocess.py:93} INFO - 4/100 ADAUSDT lưu OK
[2025-08-19T00:01:02.131+0000] {subprocess.py:93} INFO - ✅ BTCUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.131+0000] {subprocess.py:93} INFO - 5/100 BTCUSDT lưu OK
[2025-08-19T00:01:02.132+0000] {subprocess.py:93} INFO - ✅ FDUSDUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.132+0000] {subprocess.py:93} INFO - 6/100 FDUSDUSDT lưu OK
[2025-08-19T00:01:02.132+0000] {subprocess.py:93} INFO - ✅ XRPUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.132+0000] {subprocess.py:93} INFO - 7/100 XRPUSDT lưu OK
[2025-08-19T00:01:02.133+0000] {subprocess.py:93} INFO - ✅ SUIUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.133+0000] {subprocess.py:93} INFO - 8/100 SUIUSDT lưu OK
[2025-08-19T00:01:02.135+0000] {subprocess.py:93} INFO - ✅ LINKUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.135+0000] {subprocess.py:93} INFO - 9/100 LINKUSDT lưu OK
[2025-08-19T00:01:02.135+0000] {subprocess.py:93} INFO - ✅ USDCUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.136+0000] {subprocess.py:93} INFO - 10/100 USDCUSDT lưu OK
[2025-08-19T00:01:02.136+0000] {subprocess.py:93} INFO - ✅ BNBUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.137+0000] {subprocess.py:93} INFO - 11/100 BNBUSDT lưu OK
[2025-08-19T00:01:02.137+0000] {subprocess.py:93} INFO - ✅ PROVEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.138+0000] {subprocess.py:93} INFO - 12/100 PROVEUSDT lưu OK
[2025-08-19T00:01:02.138+0000] {subprocess.py:93} INFO - ✅ ENAUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.138+0000] {subprocess.py:93} INFO - 13/100 ENAUSDT lưu OK
[2025-08-19T00:01:02.139+0000] {subprocess.py:93} INFO - ✅ TRXUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.139+0000] {subprocess.py:93} INFO - 14/100 TRXUSDT lưu OK
[2025-08-19T00:01:02.140+0000] {subprocess.py:93} INFO - ✅ ARBUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.140+0000] {subprocess.py:93} INFO - 15/100 ARBUSDT lưu OK
[2025-08-19T00:01:02.140+0000] {subprocess.py:93} INFO - ✅ TOWNSUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.141+0000] {subprocess.py:93} INFO - 16/100 TOWNSUSDT lưu OK
[2025-08-19T00:01:02.141+0000] {subprocess.py:93} INFO - ✅ PEPEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.142+0000] {subprocess.py:93} INFO - 17/100 PEPEUSDT lưu OK
[2025-08-19T00:01:02.142+0000] {subprocess.py:93} INFO - ✅ UNIUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.142+0000] {subprocess.py:93} INFO - 18/100 UNIUSDT lưu OK
[2025-08-19T00:01:02.143+0000] {subprocess.py:93} INFO - ✅ AVAXUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.143+0000] {subprocess.py:93} INFO - 19/100 AVAXUSDT lưu OK
[2025-08-19T00:01:02.144+0000] {subprocess.py:93} INFO - 20/100 AEURUSDT lỗi: relation "cryptocurrency.aeurusdt" does not exist
[2025-08-19T00:01:02.144+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.aeurusdt;
[2025-08-19T00:01:02.144+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.145+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.145+0000] {subprocess.py:93} INFO - 21/100 BIOUSDT lỗi: relation "cryptocurrency.biousdt" does not exist
[2025-08-19T00:01:02.145+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.biousdt;
[2025-08-19T00:01:02.146+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.146+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.147+0000] {subprocess.py:93} INFO - ✅ PENGUUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.147+0000] {subprocess.py:93} INFO - 22/100 PENGUUSDT lưu OK
[2025-08-19T00:01:02.147+0000] {subprocess.py:93} INFO - ✅ SEIUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.148+0000] {subprocess.py:93} INFO - 23/100 SEIUSDT lưu OK
[2025-08-19T00:01:02.148+0000] {subprocess.py:93} INFO - ✅ LTCUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.149+0000] {subprocess.py:93} INFO - 24/100 LTCUSDT lưu OK
[2025-08-19T00:01:02.149+0000] {subprocess.py:93} INFO - ✅ HBARUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.149+0000] {subprocess.py:93} INFO - 25/100 HBARUSDT lưu OK
[2025-08-19T00:01:02.150+0000] {subprocess.py:93} INFO - ✅ POLUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.150+0000] {subprocess.py:93} INFO - 26/100 POLUSDT lưu OK
[2025-08-19T00:01:02.151+0000] {subprocess.py:93} INFO - 27/100 PLUMEUSDT lỗi: relation "cryptocurrency.plumeusdt" does not exist
[2025-08-19T00:01:02.151+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.plumeusdt;
[2025-08-19T00:01:02.151+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.152+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.152+0000] {subprocess.py:93} INFO - ✅ TRUMPUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.152+0000] {subprocess.py:93} INFO - 28/100 TRUMPUSDT lưu OK
[2025-08-19T00:01:02.153+0000] {subprocess.py:93} INFO - ✅ AAVEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.153+0000] {subprocess.py:93} INFO - 29/100 AAVEUSDT lưu OK
[2025-08-19T00:01:02.154+0000] {subprocess.py:93} INFO - ✅ WLDUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.154+0000] {subprocess.py:93} INFO - 30/100 WLDUSDT lưu OK
[2025-08-19T00:01:02.154+0000] {subprocess.py:93} INFO - ✅ CRVUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.155+0000] {subprocess.py:93} INFO - 31/100 CRVUSDT lưu OK
[2025-08-19T00:01:02.155+0000] {subprocess.py:93} INFO - ✅ BFUSDUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.156+0000] {subprocess.py:93} INFO - 32/100 BFUSDUSDT lưu OK
[2025-08-19T00:01:02.156+0000] {subprocess.py:93} INFO - ✅ DOTUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.156+0000] {subprocess.py:93} INFO - 33/100 DOTUSDT lưu OK
[2025-08-19T00:01:02.157+0000] {subprocess.py:93} INFO - ✅ NEARUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.157+0000] {subprocess.py:93} INFO - 34/100 NEARUSDT lưu OK
[2025-08-19T00:01:02.157+0000] {subprocess.py:93} INFO - 35/100 VIRTUALUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.158+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.158+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.159+0000] {subprocess.py:93} INFO - 36/100 INJUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.159+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.160+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.160+0000] {subprocess.py:93} INFO - 37/100 BONKUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.160+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.161+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.161+0000] {subprocess.py:93} INFO - 38/100 XLMUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.161+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.162+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.162+0000] {subprocess.py:93} INFO - 39/100 LDOUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.163+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.163+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.163+0000] {subprocess.py:93} INFO - 40/100 API3USDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.164+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.164+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.165+0000] {subprocess.py:93} INFO - 41/100 SUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.165+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.165+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.166+0000] {subprocess.py:93} INFO - 42/100 TAOUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.166+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.167+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.167+0000] {subprocess.py:93} INFO - 43/100 WIFUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.167+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.168+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.168+0000] {subprocess.py:93} INFO - ✅ FETUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.169+0000] {subprocess.py:93} INFO - 44/100 FETUSDT lưu OK
[2025-08-19T00:01:02.169+0000] {subprocess.py:93} INFO - ✅ APTUSDT: thêm 9 dòng mới
[2025-08-19T00:01:02.169+0000] {subprocess.py:93} INFO - 45/100 APTUSDT lưu OK
[2025-08-19T00:01:02.170+0000] {subprocess.py:93} INFO - ✅ PENDLEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.170+0000] {subprocess.py:93} INFO - ✅ SKLUSDT: thêm 9 dòng mới
[2025-08-19T00:01:02.171+0000] {subprocess.py:93} INFO - 46/100 PENDLEUSDT lưu OK
[2025-08-19T00:01:02.171+0000] {subprocess.py:93} INFO - 47/100 SKLUSDT lưu OK
[2025-08-19T00:01:02.171+0000] {subprocess.py:93} INFO - ✅ TONUSDT: thêm 5 dòng mới
[2025-08-19T00:01:02.172+0000] {subprocess.py:93} INFO - ✅ FLOKIUSDT: thêm 9 dòng mới
[2025-08-19T00:01:02.172+0000] {subprocess.py:93} INFO - ✅ ONDOUSDT: thêm 5 dòng mới
[2025-08-19T00:01:02.173+0000] {subprocess.py:93} INFO - ✅ OPUSDT: thêm 9 dòng mới
[2025-08-19T00:01:02.173+0000] {subprocess.py:93} INFO - 48/100 TONUSDT lưu OK
[2025-08-19T00:01:02.173+0000] {subprocess.py:93} INFO - 49/100 ONDOUSDT lưu OK
[2025-08-19T00:01:02.174+0000] {subprocess.py:93} INFO - 50/100 FLOKIUSDT lưu OK
[2025-08-19T00:01:02.174+0000] {subprocess.py:93} INFO - ✅ ETHFIUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.175+0000] {subprocess.py:93} INFO - 51/100 ETHFIUSDT lưu OK
[2025-08-19T00:01:02.175+0000] {subprocess.py:93} INFO - 52/100 OPUSDT lưu OK
[2025-08-19T00:01:02.175+0000] {subprocess.py:93} INFO - ✅ EURUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.176+0000] {subprocess.py:93} INFO - 53/100 EURUSDT lưu OK
[2025-08-19T00:01:02.176+0000] {subprocess.py:93} INFO - 54/100 PONDUSDT lỗi: relation "cryptocurrency.pondusdt" does not exist
[2025-08-19T00:01:02.177+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.pondusdt;
[2025-08-19T00:01:02.177+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.177+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.178+0000] {subprocess.py:93} INFO - ✅ BCHUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.178+0000] {subprocess.py:93} INFO - 55/100 BCHUSDT lưu OK
[2025-08-19T00:01:02.179+0000] {subprocess.py:93} INFO - ✅ TIAUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.179+0000] {subprocess.py:93} INFO - 56/100 TIAUSDT lưu OK
[2025-08-19T00:01:02.179+0000] {subprocess.py:93} INFO - ✅ SHIBUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.180+0000] {subprocess.py:93} INFO - ✅ PNUTUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.180+0000] {subprocess.py:93} INFO - 57/100 SHIBUSDT lưu OK
[2025-08-19T00:01:02.181+0000] {subprocess.py:93} INFO - 58/100 PNUTUSDT lưu OK
[2025-08-19T00:01:02.181+0000] {subprocess.py:93} INFO - ✅ EPICUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.181+0000] {subprocess.py:93} INFO - 59/100 EPICUSDT lưu OK
[2025-08-19T00:01:02.182+0000] {subprocess.py:93} INFO - ✅ NEIROUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.182+0000] {subprocess.py:93} INFO - 60/100 NEIROUSDT lưu OK
[2025-08-19T00:01:02.183+0000] {subprocess.py:93} INFO - ✅ RAYUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.183+0000] {subprocess.py:93} INFO - 61/100 RAYUSDT lưu OK
[2025-08-19T00:01:02.183+0000] {subprocess.py:93} INFO - ✅ ETCUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.184+0000] {subprocess.py:93} INFO - 62/100 ETCUSDT lưu OK
[2025-08-19T00:01:02.184+0000] {subprocess.py:93} INFO - ✅ ALGOUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.185+0000] {subprocess.py:93} INFO - 63/100 ALGOUSDT lưu OK
[2025-08-19T00:01:02.185+0000] {subprocess.py:93} INFO - 64/100 MEMEUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:02.185+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:02.186+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.186+0000] {subprocess.py:93} INFO - ✅ FILUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.187+0000] {subprocess.py:93} INFO - 65/100 FILUSDT lưu OK
[2025-08-19T00:01:02.187+0000] {subprocess.py:93} INFO - ✅ EIGENUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.188+0000] {subprocess.py:93} INFO - 66/100 EIGENUSDT lưu OK
[2025-08-19T00:01:02.188+0000] {subprocess.py:93} INFO - ✅ ALPINEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.188+0000] {subprocess.py:93} INFO - 67/100 ALPINEUSDT lưu OK
[2025-08-19T00:01:02.189+0000] {subprocess.py:93} INFO - ✅ XUSDUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.189+0000] {subprocess.py:93} INFO - 68/100 XUSDUSDT lưu OK
[2025-08-19T00:01:02.190+0000] {subprocess.py:93} INFO - ✅ MAGICUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.190+0000] {subprocess.py:93} INFO - 69/100 MAGICUSDT lưu OK
[2025-08-19T00:01:02.190+0000] {subprocess.py:93} INFO - ✅ RENDERUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.191+0000] {subprocess.py:93} INFO - 70/100 RENDERUSDT lưu OK
[2025-08-19T00:01:02.191+0000] {subprocess.py:93} INFO - ✅ GALAUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.192+0000] {subprocess.py:93} INFO - 71/100 GALAUSDT lưu OK
[2025-08-19T00:01:02.192+0000] {subprocess.py:93} INFO - ✅ JUVUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.193+0000] {subprocess.py:93} INFO - 72/100 JUVUSDT lưu OK
[2025-08-19T00:01:02.193+0000] {subprocess.py:93} INFO - 73/100 CYBERUSDT lỗi: relation "cryptocurrency.cyberusdt" does not exist
[2025-08-19T00:01:02.193+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.cyberusdt;
[2025-08-19T00:01:02.194+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.194+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.195+0000] {subprocess.py:93} INFO - ✅ CTSIUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.195+0000] {subprocess.py:93} INFO - 74/100 CTSIUSDT lưu OK
[2025-08-19T00:01:02.195+0000] {subprocess.py:93} INFO - ✅ CAKEUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.196+0000] {subprocess.py:93} INFO - 75/100 CAKEUSDT lưu OK
[2025-08-19T00:01:02.196+0000] {subprocess.py:93} INFO - ✅ SPKUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.197+0000] {subprocess.py:93} INFO - 76/100 SPKUSDT lưu OK
[2025-08-19T00:01:02.197+0000] {subprocess.py:93} INFO - ✅ OGUSDT: thêm 4 dòng mới
[2025-08-19T00:01:02.197+0000] {subprocess.py:93} INFO - 77/100 OGUSDT lưu OK
[2025-08-19T00:01:02.198+0000] {subprocess.py:93} INFO - ⚠️ WBTCUSDT lỗi lần 1/3: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=WBTCUSDT&interval=1m&limit=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9de4150bb0>, 'Connection to api.binance.com timed out. (connect timeout=15)'))
[2025-08-19T00:01:02.198+0000] {subprocess.py:93} INFO - 78/100 WBTCUSDT lỗi: relation "cryptocurrency.wbtcusdt" does not exist
[2025-08-19T00:01:02.199+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.wbtcusdt;
[2025-08-19T00:01:02.199+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.200+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:02.200+0000] {subprocess.py:93} INFO - 79/100 MKRUSDT lỗi: relation "cryptocurrency.mkrusdt" does not exist
[2025-08-19T00:01:02.201+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.mkrusdt;
[2025-08-19T00:01:02.201+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:02.201+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.873+0000] {subprocess.py:93} INFO - ⚠️ ORDIUSDT lỗi lần 1/3: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=ORDIUSDT&interval=1m&limit=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9de413ae90>, 'Connection to api.binance.com timed out. (connect timeout=15)'))
[2025-08-19T00:01:54.874+0000] {subprocess.py:93} INFO - ⚠️ ORDIUSDT lỗi lần 2/3: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v3/klines?symbol=ORDIUSDT&interval=1m&limit=100 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f9de413b6a0>, 'Connection to api.binance.com timed out. (connect timeout=15)'))
[2025-08-19T00:01:54.874+0000] {subprocess.py:93} INFO - ✅ ORDIUSDT: thêm 15 dòng mới
[2025-08-19T00:01:54.874+0000] {subprocess.py:93} INFO - 80/100 ORDIUSDT lưu OK
[2025-08-19T00:01:54.875+0000] {subprocess.py:93} INFO - ✅ MAVUSDT: thêm 28 dòng mới
[2025-08-19T00:01:54.875+0000] {subprocess.py:93} INFO - 81/100 MAVUSDT lưu OK
[2025-08-19T00:01:54.875+0000] {subprocess.py:93} INFO - 82/100 ATOMUSDT lỗi: relation "cryptocurrency.atomusdt" does not exist
[2025-08-19T00:01:54.875+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.atomusdt;
[2025-08-19T00:01:54.875+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:54.876+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.876+0000] {subprocess.py:93} INFO - ✅ SYRUPUSDT: thêm 10 dòng mới
[2025-08-19T00:01:54.876+0000] {subprocess.py:93} INFO - 83/100 SYRUPUSDT lưu OK
[2025-08-19T00:01:54.876+0000] {subprocess.py:93} INFO - ✅ ENSUSDT: thêm 23 dòng mới
[2025-08-19T00:01:54.876+0000] {subprocess.py:93} INFO - 84/100 ENSUSDT lưu OK
[2025-08-19T00:01:54.877+0000] {subprocess.py:93} INFO - 85/100 AIXBTUSDT lỗi: relation "cryptocurrency.aixbtusdt" does not exist
[2025-08-19T00:01:54.877+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.aixbtusdt;
[2025-08-19T00:01:54.877+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:54.877+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.877+0000] {subprocess.py:93} INFO - 86/100 RESOLVUSDT lỗi: relation "cryptocurrency.resolvusdt" does not exist
[2025-08-19T00:01:54.878+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.resolvusdt;
[2025-08-19T00:01:54.878+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:54.878+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.878+0000] {subprocess.py:93} INFO - ✅ ARKMUSDT: thêm 18 dòng mới
[2025-08-19T00:01:54.878+0000] {subprocess.py:93} INFO - 87/100 ARKMUSDT lưu OK
[2025-08-19T00:01:54.879+0000] {subprocess.py:93} INFO - 88/100 LAYERUSDT lỗi: relation "cryptocurrency.layerusdt" does not exist
[2025-08-19T00:01:54.879+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.layerusdt;
[2025-08-19T00:01:54.879+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:54.879+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.879+0000] {subprocess.py:93} INFO - ✅ OMUSDT: thêm 5 dòng mới
[2025-08-19T00:01:54.880+0000] {subprocess.py:93} INFO - 89/100 OMUSDT lưu OK
[2025-08-19T00:01:54.880+0000] {subprocess.py:93} INFO - 90/100 WCTUSDT lỗi: relation "cryptocurrency.wctusdt" does not exist
[2025-08-19T00:01:54.880+0000] {subprocess.py:93} INFO - LINE 1: SELECT MAX(time) FROM cryptocurrency.wctusdt;
[2025-08-19T00:01:54.880+0000] {subprocess.py:93} INFO -                               ^
[2025-08-19T00:01:54.880+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.881+0000] {subprocess.py:93} INFO - ✅ PORTOUSDT: thêm 9 dòng mới
[2025-08-19T00:01:54.881+0000] {subprocess.py:93} INFO - 91/100 PORTOUSDT lưu OK
[2025-08-19T00:01:54.881+0000] {subprocess.py:93} INFO - 92/100 PAXGUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.881+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.881+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.882+0000] {subprocess.py:93} INFO - 93/100 RUNEUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.882+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.882+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.883+0000] {subprocess.py:93} INFO - 94/100 TSTUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.883+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.883+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.883+0000] {subprocess.py:93} INFO - 95/100 CFXUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.883+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.884+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.884+0000] {subprocess.py:93} INFO - 96/100 MDTUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.884+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.884+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.884+0000] {subprocess.py:93} INFO - 97/100 VETUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.885+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.885+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.885+0000] {subprocess.py:93} INFO - 98/100 ASRUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.885+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.885+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.886+0000] {subprocess.py:93} INFO - 99/100 ICPUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.886+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.886+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.886+0000] {subprocess.py:93} INFO - 100/100 BERAUSDT lỗi: connection to server at "videv.cloud" (27.74.74.29), port 5432 failed: Connection timed out
[2025-08-19T00:01:54.886+0000] {subprocess.py:93} INFO - 	Is the server running on that host and accepting TCP/IP connections?
[2025-08-19T00:01:54.887+0000] {subprocess.py:93} INFO - 
[2025-08-19T00:01:54.979+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-08-19T00:01:54.980+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T00:01:55.016+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=crypto_collector_dag, task_id=run_crypto_collector, run_id=scheduled__2025-08-18T23:56:00+00:00, execution_date=20250818T235600, start_date=20250818T235727, end_date=20250819T000155
[2025-08-19T00:01:55.072+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T00:01:55.094+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T00:01:55.095+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
