[2025-08-18T03:47:40.375+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-18T03:47:40.420+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: update_stock_history.run_get_py manual__2025-08-18T03:44:13.157876+00:00 [queued]>
[2025-08-18T03:47:40.435+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: update_stock_history.run_get_py manual__2025-08-18T03:44:13.157876+00:00 [queued]>
[2025-08-18T03:47:40.435+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-18T03:47:40.458+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): run_get_py> on 2025-08-18 03:44:13.157876+00:00
[2025-08-18T03:47:40.465+0000] {standard_task_runner.py:63} INFO - Started process 101944 to run task
[2025-08-18T03:47:40.470+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'update_stock_history', 'run_get_py', 'manual__2025-08-18T03:44:13.157876+00:00', '--job-id', '8270', '--raw', '--subdir', 'DAGS_FOLDER/crawlchart/dags.py', '--cfg-path', '/tmp/tmplqs_cj_l']
[2025-08-18T03:47:40.471+0000] {standard_task_runner.py:91} INFO - Job 8270: Subtask run_get_py
[2025-08-18T03:47:40.523+0000] {task_command.py:426} INFO - Running <TaskInstance: update_stock_history.run_get_py manual__2025-08-18T03:44:13.157876+00:00 [running]> on host 1877907bc043
[2025-08-18T03:47:40.615+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='update_stock_history' AIRFLOW_CTX_TASK_ID='run_get_py' AIRFLOW_CTX_EXECUTION_DATE='2025-08-18T03:44:13.157876+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-18T03:44:13.157876+00:00'
[2025-08-18T03:47:40.616+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-18T03:47:40.629+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-18T03:47:40.630+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /www/server/***/dags/crawlchart/get.py']
[2025-08-18T03:47:40.641+0000] {subprocess.py:86} INFO - Output:
[2025-08-18T03:47:40.746+0000] {subprocess.py:93} INFO - python3: can't open file '/www/server/***/dags/crawlchart/get.py': [Errno 2] No such file or directory
[2025-08-18T03:47:40.751+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2025-08-18T03:47:40.752+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-18T03:47:40.765+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2025-08-18T03:47:40.768+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=update_stock_history, task_id=run_get_py, run_id=manual__2025-08-18T03:44:13.157876+00:00, execution_date=20250818T034413, start_date=20250818T034740, end_date=20250818T034740
[2025-08-18T03:47:40.779+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 8270 for task run_get_py (Bash command failed. The command returned a non-zero exit code 2.; 101944)
[2025-08-18T03:47:40.802+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-18T03:47:40.841+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-18T03:47:40.843+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
